### ISSUE TITLE
Problems where item placement is broken.

### ISSUE THREAD

**Issue by JoonDong2** [Feng-Bu-Jue/react-native-waterfall#4]
If the height of the item changes dynamically or a new item is added to the start, existing items are overlapped or empty spaces appear.

How can I solve this problem?

**Comment by Feng-Bu-Jue** [comment]
At present, dynamic height is not supported. you should call ref.reset() if item's height changes

**Comment by JoonDong2** [comment]
> At present, dynamic height is not supported. you should call ref.reset() if item's height changes

I understand. 
Thank you!!
