### ISSUE TITLE
高度可否不要从itemData里面取.

### ISSUE THREAD

**Issue by jamninetyfive** [Feng-Bu-Jue/react-native-waterfall#5]
height: itemInfoData[i].size

高度可否不要从itemData里面取. 想写死还得改下数据结构。

**Comment by jamninetyfive** [comment]
因为我现有数据里面有size字段了

**Comment by Feng-Bu-Jue** [comment]
请使用最新的1.2.0版本
已经增加了 heightGetter 属性, 还有一些props 修改（参考源码里的props type readme之后有空在更新）
