### ISSUE TITLE
Does wrapping the item with React.memo help improve the performance?

### ISSUE THREAD

**Issue by JoonDong2** [Feng-Bu-Jue/react-native-waterfall#6]
Thank you for making good library.
But I have a question. Does wrapping the item with React.memo help improve the performance?

Thank you.

**Comment by Feng-Bu-Jue** [comment]
make waterfall as the root node in your component should not require to react.memo

**Comment by JoonDong2** [comment]
> make waterfall as the root node in your component should not require to react.memo

Thank you.
