### ISSUE TITLE
Waterfall demo won't run on Firefox

### ISSUE THREAD

**Issue by thekingofcity** [Feng-Bu-Jue/react-native-waterfall#7]
The right panel showes completely blank on Firefox 88.0.1 Windows 20H2 19042

`Uncaught ReferenceError: BrowserFS is not defined`

---

However on Chrome 91.0.4472.164 it displays correctly.

**Comment by Feng-Bu-Jue** [comment]
I checked it with Firefox 89.0.2 and it working fine. 
I'm not sure if it's a codesandbox problem
[issue](https://github.com/codesandbox/codesandbox-client/issues/2842)

**Comment by thekingofcity** [comment]
It is beacuse I enabled `Enhanced Tracking Protection` in Firefox, disabling it will fix the error.

Sorry to bother you :(
